import React,{act} from 'react';
import {createRoot} from 'react-dom/client';
import App from '../customer-web/src/App';
window.IS_REACT_ACT_ENVIRONMENT=true;
window.__scanners=[];
Object.defineProperty(window,'isSecureContext',{value:true});
Object.defineProperty(navigator,'mediaDevices',{value:{getUserMedia:async()=>({})}});
const vibrations=[],orders=[],checks=[];
navigator.vibrate=duration=>{vibrations.push(duration);return true;};
window.fetch=async(url,options={})=>{if(String(url).endsWith('/create-order'))orders.push(JSON.parse(options.body).package);return {ok:true,status:200,json:async()=>({requestId:'new-request',orderId:'test-order',amount:1700,keyId:'fixture',serviceType:'HEALTH_CHECKUP',status:'CREATED'})};};
const root=createRoot(document.getElementById('app'));
const wait=()=>act(async()=>new Promise(r=>setTimeout(r,30)));
const assert=(ok,message)=>{if(!ok)throw Error(message);checks.push('PASS '+message);};
const button=text=>[...document.querySelectorAll('button')].find(b=>b.textContent===text);
async function run(){
 localStorage.clear();sessionStorage.clear();window.history.replaceState(null,'','/scan');
 await act(async()=>root.render(<App/>));await wait();
 let scanner=window.__scanners.at(-1);assert(scanner,'direct scan route opens scanner');
 assert(scanner.options.maxScansPerSecond===25,'scan attempts capped at camera-friendly 25fps');
 await act(async()=>{for(let i=0;i<3;i++)scanner.onDecode({data:'https://evil.example/pay#p=bad'});});
 assert(!vibrations.length&&!orders.length,'untrusted QR never vibrates or creates an order');
 const qr='https://reliv7.vercel.app/pay#p=current_encrypted-package';
 await act(async()=>{scanner.onDecode({data:qr});scanner.onDecode({data:qr});});await wait();
 assert(vibrations.length===1&&vibrations[0]===1000,'exactly one one-second vibration per accepted QR');
 assert(scanner.destroyed,'camera decoder destroyed before checkout');
 assert(location.pathname==='/pay'&&location.hash==='#p=current_encrypted-package','package transferred without leaving current origin');
 assert(orders.length===1&&orders[0]==='current_encrypted-package','only scanned package creates an order, exactly once');
 assert(document.body.textContent.includes('QR captured'),'visible scan confirmation without a page reload');
 await act(async()=>button('Scan kiosk payment QR').click());await wait();
 scanner=window.__scanners.at(-1);
 await act(async()=>button('Close').click());await wait();
 const before=orders.length;await act(async()=>scanner.onDecode({data:qr}));
 assert(scanner.destroyed&&orders.length===before,'late decoder callback after close cannot navigate');
 window.__denyCamera=true;
 await act(async()=>button('Scan kiosk payment QR').click());await wait();
 assert(button('Retry camera'),'permission failure offers retry');
 window.__denyCamera=false;await act(async()=>button('Retry camera').click());await wait();
 scanner=window.__scanners.at(-1);assert(scanner.starts===1&&!scanner.destroyed,'retry creates a fresh camera instance');
 const beforeDemoOrders=orders.length, beforeDemoVibrations=vibrations.length;
 const demo=JSON.stringify({type:'RELIV_DEMO_SAMPLE',status:'NOT_PAYABLE',padding:'x'.repeat(1900)});
 await act(async()=>{scanner.onDecode({data:demo});scanner.onDecode({data:demo});});
 assert(document.body.textContent.includes('Demo QR scanned successfully'),'demo immediately confirms decoding rather than claiming scan failure');
 assert(scanner.destroyed&&vibrations.length===beforeDemoVibrations+1,'demo releases camera and acknowledges exactly once');
 assert(orders.length===beforeDemoOrders,'demo never creates a payment order');
 await act(async()=>scanner.onDecode({data:qr}));
 assert(orders.length===beforeDemoOrders,'late frame after demo cannot initiate payment');
 await act(async()=>button('Scan another QR').click());await wait();
 scanner=window.__scanners.at(-1);
 assert(scanner.starts===1&&!scanner.destroyed&&!document.body.textContent.includes('Demo QR scanned successfully'),'scan another QR resets demo state and restarts camera');
 await act(async()=>root.unmount());assert(scanner.destroyed,'unmount releases camera');
 document.getElementById('results').textContent=checks.join('\n')+'\nALL '+checks.length+' BROWSER CHECKS PASSED';
}
run().catch(e=>{document.getElementById('results').textContent=checks.join('\n')+'\nFAIL '+e.stack;});
