export const entryCopy={
 en:{welcome:'Welcome. How can we help?',new:'My first health check',returning:'I have checked here before',medicine:'Buy medicine or a kit',newHint:'Create your private record',returnHint:'Use your name and PIN',medicineHint:'No health PIN needed',choose:'For your first health check, tap My first health check. If you have checked here before, use your name and your own PIN. To buy an item, choose Buy medicine or a kit.',name:'Your name',nameHelp:'Tap the name box and type your name. Use the same name on your next visit. Then tap Continue.',age:'Your age',gender:'Gender',details:'A little about you',detailsHelp:'Enter your age in years. Choose your gender. Then tap Continue. There is no email or phone number to enter.',male:'Male',female:'Female',other:'Other',pin:'Create your own 6-digit PIN',returnPin:'Enter your 6-digit PIN',pinHelp:'Choose six numbers yourself. This is your private PIN, not a code sent to your phone. Remember it. On your next visit, use the same name and PIN. You only need to enter it once.',returnHelp:'Enter the six numbers you chose on your first visit. This kiosk checks them locally to link your scans. If you forgot your PIN, ask staff for help.',show:'Show PIN',hide:'Hide PIN',continue:'Continue',start:'Start my visit',back:'Back',change:'Change my choice',saving:'Please wait. Saving your details.',error:'Could not continue. Check your details and try again. If you forgot your PIN, ask staff.',wrong:'Name or PIN did not match. Try again or ask staff.',delete:'Delete last digit',step:'Step',done:'Done'},
 hi:{welcome:'स्वागत है। आपको क्या चाहिए?',new:'मेरी पहली स्वास्थ्य जाँच',returning:'मैं पहले यहाँ जाँच करा चुका हूँ',medicine:'दवा या किट खरीदें',newHint:'अपना निजी रिकॉर्ड बनाएँ',returnHint:'अपना नाम और PIN डालें',medicineHint:'स्वास्थ्य PIN की ज़रूरत नहीं',choose:'पहली जाँच के लिए मेरी पहली स्वास्थ्य जाँच दबाएँ। पहले जाँच कराई है तो अपना नाम और अपना PIN डालें। सामान खरीदना हो तो दवा या किट खरीदें चुनें।',name:'आपका नाम',nameHelp:'नाम के खाने को छुएँ और अपना नाम लिखें। अगली बार भी यही नाम डालें। फिर आगे बढ़ें दबाएँ।',age:'आपकी उम्र',gender:'लिंग',details:'आपके बारे में',detailsHelp:'अपनी उम्र वर्षों में डालें। अपना लिंग चुनें। फिर आगे बढ़ें दबाएँ। ईमेल या फोन नंबर नहीं चाहिए।',male:'पुरुष',female:'महिला',other:'अन्य',pin:'अपना 6 अंकों का PIN बनाएँ',returnPin:'अपना 6 अंकों का PIN डालें',pinHelp:'अपनी पसंद के छह अंक चुनें। यह आपका निजी PIN है, फोन पर आने वाला कोड नहीं। इसे याद रखें। अगली बार यही नाम और PIN डालें। केवल एक बार डालना है।',returnHelp:'पहली बार चुने गए छह अंक डालें। मशीन यहीं जाँच करके आपकी पुरानी जाँच जोड़ेगी। PIN भूल गए हों तो कर्मचारी की मदद लें।',show:'PIN दिखाएँ',hide:'PIN छिपाएँ',continue:'आगे बढ़ें',start:'मेरी जाँच शुरू करें',back:'पीछे',change:'चुनाव बदलें',saving:'कृपया रुकें। जानकारी सहेज रहे हैं।',error:'आगे नहीं बढ़ पाए। जानकारी जाँचकर फिर कोशिश करें। PIN भूल गए हों तो कर्मचारी की मदद लें।',wrong:'नाम या PIN नहीं मिला। फिर कोशिश करें या कर्मचारी की मदद लें।',delete:'आखिरी अंक मिटाएँ',step:'कदम',done:'पूरा हुआ'},
 bn:{welcome:'স্বাগত। কীভাবে সাহায্য করব?',new:'আমার প্রথম স্বাস্থ্য পরীক্ষা',returning:'আগেও এখানে পরীক্ষা করিয়েছি',medicine:'ওষুধ বা কিট কিনব',newHint:'আপনার ব্যক্তিগত রেকর্ড তৈরি করুন',returnHint:'আপনার নাম ও PIN দিন',medicineHint:'স্বাস্থ্য PIN লাগবে না',choose:'প্রথম পরীক্ষার জন্য আমার প্রথম স্বাস্থ্য পরীক্ষা চাপুন। আগে পরীক্ষা করালে নিজের নাম ও নিজের PIN দিন। জিনিস কিনতে হলে ওষুধ বা কিট কিনব বেছে নিন।',name:'আপনার নাম',nameHelp:'নামের ঘর ছুঁয়ে নিজের নাম লিখুন। পরেরবারও একই নাম দিন। তারপর এগিয়ে যান চাপুন।',age:'আপনার বয়স',gender:'লিঙ্গ',details:'আপনার সম্পর্কে',detailsHelp:'আপনার বয়স বছরে লিখুন। লিঙ্গ বেছে নিন। তারপর এগিয়ে যান চাপুন। ইমেল বা ফোন নম্বর লাগবে না।',male:'পুরুষ',female:'মহিলা',other:'অন্যান্য',pin:'নিজের ৬ সংখ্যার PIN তৈরি করুন',returnPin:'আপনার ৬ সংখ্যার PIN দিন',pinHelp:'নিজের পছন্দের ছয়টি সংখ্যা বেছে নিন। এটি ব্যক্তিগত PIN, ফোনে আসা কোড নয়। মনে রাখুন। পরেরবার একই নাম ও PIN ব্যবহার করুন। একবারই লিখতে হবে।',returnHelp:'প্রথমবার বেছে নেওয়া ছয়টি সংখ্যা লিখুন। এই কিয়স্ক এখানেই মিলিয়ে আপনার আগের পরীক্ষা যুক্ত করবে। PIN ভুলে গেলে কর্মীর সাহায্য নিন।',show:'PIN দেখান',hide:'PIN লুকান',continue:'এগিয়ে যান',start:'আমার পরীক্ষা শুরু করুন',back:'পিছনে',change:'পছন্দ বদলান',saving:'একটু অপেক্ষা করুন। তথ্য রাখা হচ্ছে।',error:'এগোনো যায়নি। তথ্য দেখে আবার চেষ্টা করুন। PIN ভুলে গেলে কর্মীর সাহায্য নিন।',wrong:'নাম বা PIN মেলেনি। আবার চেষ্টা করুন বা কর্মীর সাহায্য নিন।',delete:'শেষ সংখ্যা মুছুন',step:'ধাপ',done:'হয়েছে'}
};
export const paymentValue={
 en:'Your paid health report has five pages explaining today’s measured results in simple language, with spoken help. Your first scan is a starting point. Future scans linked by your name and PIN add comparisons using real measurements. It is screening information, not a diagnosis. The price shown on this screen is the amount to pay.',
 hi:'भुगतान के बाद पाँच पृष्ठों में आज के असली माप आसान भाषा और आवाज़ में समझाए जाएँगे। पहली जाँच आगे की तुलना का आधार है। अगली बार उसी नाम और PIN से असली मापों की तुलना जुड़ेगी। यह प्रारंभिक जाँच है, बीमारी का निदान नहीं। स्क्रीन पर दिख रही कीमत ही देनी है।',
 bn:'টাকা দেওয়ার পরে পাঁচ পৃষ্ঠায় আজকের আসল মাপ সহজ ভাষায় ও কথায় বুঝিয়ে দেওয়া হবে। প্রথম পরীক্ষা পরের তুলনার ভিত্তি। একই নাম ও PIN দিয়ে পরেরবার বাস্তব মাপের তুলনা যোগ হবে। এটি প্রাথমিক পরীক্ষা, রোগ নির্ণয় নয়। স্ক্রিনে দেখানো দামই দিতে হবে।'
};
