import { getScanCount, reportMeasurements } from '../utils/reportSnapshot.js';
import { reportNarration } from './reportQuestions.js';

export const reportCopy = {
 en: { title:'Your health report', scan:'Scan', page:'Page', back:'Back', next:'Next page', finish:'Finish my visit', missing:'Not measured', estimated:'Estimated, not a diagnosis', years:'years', age:'Your age', metabolic:'Metabolic age', unavailable:'A reliable metabolic-age estimate is not available from these measurements. Your actual readings are shown on the next page.', titles:['Your body overview','Today’s measurements','Your progress graph','Your scan comparisons','Your summary & next steps'], guides:[
 'Welcome to your five-page report. Take your time. This first page introduces your body measurements. Metabolic age is only an estimate, not your actual age or a diagnosis. If it is unavailable, we will say so. Tap Next page when you are ready.',
 'Here are the measurements recorded today. Blood pressure describes pressure in your blood vessels. Oxygen estimates the oxygen level in your blood. Pulse counts heartbeats, and temperature records how warm your body is. A single reading does not tell the whole story. Missing measurements stay blank.',
 'This graph follows your own readings. Choose a measurement using the buttons. One dot means one recorded scan. With another scan you can compare two points. Gaps mean a reading was missing. A rising or falling line is a change, not automatically good or bad.',
 'Each bar is one of your recorded scans. Choose a measurement to compare its values. A first scan shows one bar. Later visits add bars. Compare like with like: the same measurement and unit. Your graph uses your own records, not another person’s results.',
 'You have reached your summary. Keep a regular routine that suits you and follow advice from your clinician. For a useful comparison, repeat measurements under similar conditions. The next scan can show what changed, but cannot promise a diagnosis. If you feel unwell or a result worries you, ask a qualified clinician. Tap Finish my visit when you are done.'
 ], baseline:'This first scan is your starting point. Nothing needs to be unlocked to see these five pages.', comparison:'You now have an earlier scan to compare with today. Two readings show a difference, not a long-term trend.', trend:'With more recorded visits, patterns become easier to see. Missing measurements are never filled in.', nextTitle:'What your next scan can tell you', nextText:'Another measurement adds a real comparison. Several visits may show whether a change repeats. More scans do not guarantee a diagnosis.', improveTitle:'Your next steps', improveText:'Use this report to discuss concerns with a clinician. For fair comparisons, use similar measurement conditions. Do not change medicines based only on this kiosk.', caution:'Screening information only. This is not a diagnosis.', choose:'Choose a measurement', date:'Recorded', previous:'Previous', current:'Today', difference:'Change', none:'No earlier matching reading', privacy:'Only your privately linked scans appear here.', chart:'Last seven recorded scans', points:'Recorded values', summary:'Today’s recorded values', help:'Listen for step-by-step help.' },
 hi: { title:'आपकी स्वास्थ्य रिपोर्ट', scan:'जाँच', page:'पृष्ठ', back:'पीछे', next:'अगला पृष्ठ', finish:'मेरी जाँच समाप्त करें', missing:'माप नहीं मिला', estimated:'अनुमान है, निदान नहीं', years:'वर्ष', age:'आपकी उम्र', metabolic:'मेटाबॉलिक उम्र', unavailable:'इन मापों से भरोसेमंद मेटाबॉलिक उम्र उपलब्ध नहीं है। अगले पृष्ठ पर आपके असली माप हैं।', titles:['आपके शरीर का परिचय','आज के माप','आपकी प्रगति का ग्राफ','आपकी जाँचों की तुलना','सारांश और अगला कदम'], guides:[
 'आपकी पाँच पृष्ठों की रिपोर्ट में स्वागत है। आराम से देखें। पहले पृष्ठ पर शरीर के मापों का परिचय है। मेटाबॉलिक उम्र केवल एक अनुमान है। यह आपकी असली उम्र या बीमारी का निदान नहीं है। अनुमान उपलब्ध नहीं हो तो हम साफ बताएँगे। तैयार हों तो अगला पृष्ठ दबाएँ।',
 'ये आज दर्ज किए गए माप हैं। रक्तचाप खून की नलियों में दबाव बताता है। ऑक्सीजन खून में ऑक्सीजन का अनुमान है। नाड़ी एक मिनट की धड़कनें गिनती है। तापमान शरीर की गर्मी बताता है। एक माप पूरी कहानी नहीं बताता। जो माप नहीं मिला, उसे खाली रखा गया है।',
 'यह ग्राफ आपके अपने माप दिखाता है। बटन दबाकर माप चुनें। एक बिंदु एक दर्ज जाँच है। अगली जाँच से दो बिंदुओं की तुलना होगी। बीच में खाली जगह का मतलब माप नहीं मिला। रेखा ऊपर या नीचे जाना बदलाव है, अपने आप अच्छा या बुरा नहीं।',
 'हर खड़ी पट्टी आपकी एक जाँच है। जिस माप की तुलना चाहिए, उसका बटन दबाएँ। पहली जाँच में एक पट्टी दिखेगी। अगली बार और पट्टियाँ जुड़ेंगी। हमेशा एक ही माप और इकाई की तुलना करें। यहाँ केवल आपके अपने रिकॉर्ड हैं।',
 'यह आपकी रिपोर्ट का सारांश है। अपनी सुविधा की नियमित दिनचर्या रखें और डॉक्टर की सलाह मानें। सही तुलना के लिए अगली बार मिलती-जुलती परिस्थिति में माप लें। अगली जाँच बदलाव बता सकती है, बीमारी पहचानने की गारंटी नहीं। तबीयत खराब लगे या कोई माप चिंता दे तो डॉक्टर से बात करें। पूरा हो जाए तो मेरी जाँच समाप्त करें दबाएँ।'
 ], baseline:'यह पहली जाँच आगे की तुलना का आधार है। पाँचों पृष्ठ अभी देख सकते हैं।', comparison:'अब आज और पिछली जाँच की तुलना हो सकती है। दो माप का अंतर लंबे समय का रुझान नहीं है।', trend:'अधिक असली जाँचों से बार-बार होने वाला बदलाव समझना आसान है। कोई गायब माप बनाया नहीं जाता।', nextTitle:'अगली जाँच क्या बताएगी', nextText:'एक और जाँच असली तुलना जोड़ेगी। कई जाँचों से पता चल सकता है कि बदलाव दोहराता है या नहीं। बीमारी के निदान की गारंटी नहीं है।', improveTitle:'आपका अगला कदम', improveText:'चिंता हो तो रिपोर्ट लेकर डॉक्टर से बात करें। तुलना के लिए जाँच की परिस्थितियाँ समान रखें। केवल इस रिपोर्ट से दवा न बदलें।', caution:'यह प्रारंभिक जाँच है, बीमारी का निदान नहीं।', choose:'माप चुनें', date:'दर्ज तारीख', previous:'पिछली बार', current:'आज', difference:'बदलाव', none:'पिछला समान माप नहीं है', privacy:'केवल आपकी निजी जाँचें यहाँ दिखाई जाती हैं।', chart:'पिछली सात दर्ज जाँचें', points:'दर्ज माप', summary:'आज दर्ज किए गए माप', help:'आसान निर्देश सुनने के लिए सुनें दबाएँ।' },
 bn: { title:'আপনার স্বাস্থ্য রিপোর্ট', scan:'পরীক্ষা', page:'পৃষ্ঠা', back:'পিছনে', next:'পরের পৃষ্ঠা', finish:'আমার পরীক্ষা শেষ করুন', missing:'পরিমাপ হয়নি', estimated:'অনুমান, রোগ নির্ণয় নয়', years:'বছর', age:'আপনার বয়স', metabolic:'মেটাবলিক বয়স', unavailable:'এই মাপ থেকে নির্ভরযোগ্য মেটাবলিক বয়স পাওয়া যায়নি। পরের পৃষ্ঠায় আপনার আসল মাপ দেখুন।', titles:['আপনার শরীরের পরিচয়','আজকের পরিমাপ','আপনার অগ্রগতির গ্রাফ','আপনার পরীক্ষার তুলনা','সারাংশ ও পরের পদক্ষেপ'], guides:[
 'আপনার পাঁচ পৃষ্ঠার রিপোর্টে স্বাগত। সময় নিয়ে দেখুন। প্রথম পৃষ্ঠায় শরীরের মাপের পরিচয় আছে। মেটাবলিক বয়স শুধু একটি অনুমান। এটি আপনার আসল বয়স বা রোগ নির্ণয় নয়। অনুমান না থাকলে আমরা স্পষ্ট বলব। প্রস্তুত হলে পরের পৃষ্ঠা চাপুন।',
 'এগুলি আজকের নথিভুক্ত মাপ। রক্তচাপ রক্তনালির চাপ বোঝায়। অক্সিজেন রক্তের অক্সিজেনের আনুমানিক মাত্রা। পালস এক মিনিটের হৃদস্পন্দন গোনে। তাপমাত্রা শরীর কতটা গরম তা বলে। একটি মাপ পুরো বিষয়টি বোঝায় না। যে মাপ পাওয়া যায়নি তা ফাঁকা থাকবে।',
 'এই গ্রাফে আপনার নিজের মাপ আছে। বোতাম চেপে একটি মাপ বেছে নিন। একটি বিন্দু মানে একটি নথিভুক্ত পরীক্ষা। পরের পরীক্ষায় দুটি বিন্দু তুলনা করা যাবে। ফাঁকা জায়গা মানে মাপ পাওয়া যায়নি। রেখা ওঠা বা নামা একটি পরিবর্তন, নিজে থেকেই ভালো বা খারাপ নয়।',
 'প্রতিটি খাড়া বার আপনার একটি পরীক্ষা। যে মাপের তুলনা চান সেটি বেছে নিন। প্রথম পরীক্ষায় একটি বার থাকবে। পরের পরীক্ষায় আরও বার যোগ হবে। একই মাপ ও এককের তুলনা করুন। এখানে শুধু আপনার নিজের তথ্য আছে।',
 'এটি আপনার রিপোর্টের সারাংশ। আপনার উপযুক্ত নিয়মিত অভ্যাস রাখুন এবং চিকিৎসকের পরামর্শ মানুন। ভালো তুলনার জন্য পরেরবার একই রকম পরিস্থিতিতে মাপ নিন। পরের পরীক্ষা পরিবর্তন দেখাতে পারে, রোগ নির্ণয়ের নিশ্চয়তা দেয় না। অসুস্থ লাগলে বা চিন্তা হলে চিকিৎসকের সঙ্গে কথা বলুন। শেষ হলে আমার পরীক্ষা শেষ করুন চাপুন।'
 ], baseline:'প্রথম পরীক্ষা পরের তুলনার ভিত্তি। পাঁচটি পৃষ্ঠাই এখন দেখতে পারবেন।', comparison:'এখন আগের পরীক্ষার সঙ্গে আজকের তুলনা করা যায়। দুটি মাপের পার্থক্য দীর্ঘমেয়াদি প্রবণতা নয়।', trend:'আরও বাস্তব পরীক্ষা হলে বারবার হওয়া পরিবর্তন বোঝা সহজ হয়। অনুপস্থিত মাপ তৈরি করা হয় না।', nextTitle:'পরের পরীক্ষা কী জানাবে', nextText:'আরেকটি পরীক্ষা বাস্তব তুলনা যোগ করবে। কয়েকটি পরীক্ষায় বোঝা যেতে পারে পরিবর্তনটি আবার হচ্ছে কি না। রোগ নির্ণয়ের নিশ্চয়তা নেই।', improveTitle:'আপনার পরের পদক্ষেপ', improveText:'চিন্তা থাকলে রিপোর্ট নিয়ে চিকিৎসকের সঙ্গে কথা বলুন। তুলনার জন্য একই পরিস্থিতিতে পরীক্ষা করুন। শুধু এই রিপোর্ট দেখে ওষুধ বদলাবেন না।', caution:'এটি প্রাথমিক পরীক্ষার তথ্য, রোগ নির্ণয় নয়।', choose:'একটি মাপ বেছে নিন', date:'নথিভুক্ত তারিখ', previous:'আগেরবার', current:'আজ', difference:'পরিবর্তন', none:'আগের একই মাপ নেই', privacy:'শুধু আপনার ব্যক্তিগত পরীক্ষাগুলি এখানে আছে।', chart:'শেষ সাতটি নথিভুক্ত পরীক্ষা', points:'নথিভুক্ত মাপ', summary:'আজকের নথিভুক্ত মাপ', help:'সহজ নির্দেশ শুনতে শুনুন চাপুন।' },
};
export function reportStage(data, language) {
 const w=reportCopy[language] || reportCopy.en, count=getScanCount(data);
 return count===1 ? w.baseline : count===2 ? w.comparison : w.trend;
}
export function chartScans(data) {
 const history=Array.isArray(data.history)?data.history:[];
 const count=getScanCount(data);
 const rows=history.length ? history : [data.vitals || {}];
 return rows.slice(-7).map((row,index,all)=>({...row,scan:Math.max(1,count-all.length+1)+index}));
}
export function reportDetail(data,language,page,field='systolic') {
 const w=reportCopy[language]||reportCopy.en;
 if(page===1) return `${w.age}: ${Number(data.patient?.age)||w.missing}. ${w.metabolic}: ${Number(data.vitals?.metabolicAge)>0?`${data.vitals.metabolicAge} ${w.years}. ${w.estimated}`:w.unavailable}`;
 if(page===2||page===5) return reportNarration(data,language);
 const rows=chartScans(data),unit=reportMeasurements().find(x=>x.key===field)?.unit||'';
 return rows.map(row=>`${w.scan} ${row.scan}: ${Number(row[field])>0 ? `${row[field]} ${unit}` : w.missing}.`).join(' ');
}
