// Narration is recorded at build time, with no runtime cloud dependency.
export const insightCopy = {
 en: { all:'All measurements', measured:'Measured', calculated:'Calculated', estimated:'Population estimate', neutral:'Information', good:'Within reference', caution:'Check / repeat', review:'Needs review', urgent:'Get medical help', missing:'Not available', reference:'Adult screening reference', observations:'recorded observations', metrics:'available values today', estimates:'Body estimates use height, weight, age and the male/female equation selected in your profile. They are not sensor measurements. They may be inaccurate during pregnancy, illness, fluid changes or for athletes. Do not use them to decide how much to drink or eat.', metabolic:'Metabolic age and visceral fat need a validated assessment. This kiosk cannot measure them reliably. Resting energy below estimates energy used at rest, not a calorie target.', chart:'Each colour has its own scale and unit. Compare the same row across scans. Tap a measurement to see it alone.', composition:'Estimated body composition', water:'Water is part of fat-free mass. Do not add these percentages together.', goodAdvice:'Some readings are within the adult screening reference. This does not rule out illness. Keep the habits that work for you.', cautionAdvice:'One or more readings need a recheck. Sit quietly, repeat with the device positioned correctly, and discuss persistent changes with a clinician.', urgentAdvice:'A reading needs prompt medical attention. If you have chest pain, trouble breathing, fainting, new weakness or confusion, get emergency help now. Do not wait for another paid scan.', next:'Your next scan adds a comparison of the same measurements. Similar timing and conditions make changes easier to understand. Repeating a scan does not create new sensor measurements or guarantee better health.', numbers:'Your recorded values are read next.', summary:'Your plan for today', share:'Check in together', shareText:'Invite a friend or partner to their own private check-in. Compare consistency, not who has a healthier body. Sharing is optional.', noScore:'There is no validated overall health score from these measurements.' },
 hi: { all:'सभी माप साथ देखें', measured:'डिवाइस से मापा', calculated:'हिसाब से निकला', estimated:'फॉर्मूले से अनुमान', neutral:'जानकारी', good:'सामान्य रेंज में', caution:'दोबारा जाँचें', review:'डॉक्टर से बात करें', urgent:'मेडिकल मदद लें', missing:'उपलब्ध नहीं', reference:'बड़ों के लिए जाँच की रेंज', observations:'दर्ज किए गए माप', metrics:'आज की उपलब्ध जानकारी', estimates:'ये अनुमान आपकी लंबाई, वजन, उम्र और प्रोफाइल में चुने गए पुरुष या महिला के फॉर्मूले से निकले हैं। सेंसर ने इन्हें नहीं मापा है। प्रेग्नेंसी, बीमारी, पानी की मात्रा बदलने या एथलीट होने पर ये गलत हो सकते हैं। इनसे खाने या पानी पीने की मात्रा तय न करें।', metabolic:'मेटाबॉलिक उम्र यानी शरीर की एनर्जी को उम्र से जोड़कर लगाया गया अनुमान। अंदर के फैट और इस उम्र को यह मशीन भरोसे से नहीं बता सकती। नीचे आराम के समय लगने वाली एनर्जी का अनुमान है, खाने का टारगेट नहीं।', chart:'हर रंग की अपनी रेंज और यूनिट है। एक ही लाइन को पिछली जाँच से मिलाइए। कोई एक माप देखना हो तो उसका बटन दबाइए।', composition:'शरीर में फैट और पानी का अनुमान', water:'पानी बिना फैट वाले हिस्से में भी होता है। इन प्रतिशतों को आपस में जोड़ना सही नहीं है।', goodAdvice:'कुछ रीडिंग सामान्य रेंज में हैं। इसका मतलब यह नहीं कि हर बीमारी खारिज हो गई। अच्छी आदतें जारी रखें।', cautionAdvice:'कुछ रीडिंग दोबारा देखने की जरूरत है। आराम से बैठें, डिवाइस सही जगह रखें और फिर जाँचें। बदलाव बना रहे तो डॉक्टर से बात करें।', urgentAdvice:'एक रीडिंग के लिए जल्दी मेडिकल मदद चाहिए। सीने में दर्द, साँस लेने में दिक्कत, बेहोशी, अचानक कमजोरी या उलझन हो तो अभी इमरजेंसी मदद लें। अगली पेड जाँच का इंतजार न करें।', next:'अगली बार यही माप फिर मिलेंगे, ताकि आज से तुलना हो सके। करीब वही समय और हालात रखें। बार-बार जाँच से नए सेंसर वाले माप नहीं बनते, न अच्छी सेहत की गारंटी मिलती है।', numbers:'अब आपकी दर्ज रीडिंग सुनिए।', summary:'आज आपके लिए क्या करना ठीक रहेगा', share:'दोस्त के साथ सेहत पर ध्यान दें', shareText:'दोस्त या पार्टनर को अपनी अलग, निजी जाँच के लिए बुलाएँ। नियमित ध्यान देने की तुलना करें, शरीर में कौन बेहतर है उसकी नहीं। शेयर करना आपकी मर्जी है।', noScore:'इन मापों से पूरी सेहत का भरोसेमंद स्कोर नहीं निकलता।' },
 bn: { all:'সব মাপ একসঙ্গে', measured:'যন্ত্রে মাপা', calculated:'হিসাব করা', estimated:'ফর্মুলার অনুমান', neutral:'তথ্য', good:'সাধারণ সীমার মধ্যে', caution:'আবার মাপুন', review:'ডাক্তারের সঙ্গে কথা বলুন', urgent:'চিকিৎসার সাহায্য নিন', missing:'পাওয়া যায়নি', reference:'বড়দের পরীক্ষার সাধারণ সীমা', observations:'নথিভুক্ত মাপ', metrics:'আজকের পাওয়া তথ্য', estimates:'এই অনুমান উচ্চতা, ওজন, বয়স আর প্রোফাইলে বেছে নেওয়া পুরুষ বা মহিলার ফর্মুলা দিয়ে করা। সেন্সরে মাপা নয়। প্রেগন্যান্সি, অসুখ, শরীরের জল বদলালে বা অ্যাথলিট হলে ভুল হতে পারে। কতটা খাবেন বা জল খাবেন, তা এগুলি দিয়ে ঠিক করবেন না।', metabolic:'মেটাবলিক বয়স হল শরীরের এনার্জিকে বয়সের সঙ্গে মিলিয়ে করা অনুমান। এই যন্ত্রে তা বা ভেতরের ফ্যাট নির্ভরযোগ্যভাবে মাপা যায় না। নিচে বিশ্রামের সময় কতটা এনার্জি লাগে তার অনুমান আছে, খাবারের টার্গেট নয়।', chart:'প্রতিটি রঙের নিজের স্কেল আর একক আছে। একই লাইনে আগের পরীক্ষার সঙ্গে তুলনা করুন। একটি মাপ দেখতে তার বোতাম চাপুন।', composition:'শরীরের ফ্যাট আর জলের অনুমান', water:'জল ফ্যাট ছাড়া শরীরের অংশের মধ্যেও থাকে। এই শতাংশগুলি যোগ করবেন না।', goodAdvice:'কিছু রিডিং সাধারণ সীমার মধ্যে আছে। তার মানে সব অসুখ নেই এমন নয়। ভালো অভ্যাসগুলি চালিয়ে যান।', cautionAdvice:'কিছু রিডিং আবার দেখা দরকার। শান্ত হয়ে বসুন, যন্ত্র ঠিক জায়গায় রেখে আবার মাপুন। বদল থেকে গেলে ডাক্তারের সঙ্গে কথা বলুন।', urgentAdvice:'একটি রিডিংয়ের জন্য দ্রুত চিকিৎসার সাহায্য দরকার। বুকে ব্যথা, শ্বাসকষ্ট, অজ্ঞান হওয়া, হঠাৎ দুর্বলতা বা বিভ্রান্তি হলে এখনই জরুরি সাহায্য নিন। পরের পেড পরীক্ষার অপেক্ষা করবেন না।', next:'পরের পরীক্ষায় একই মাপ আবার পাওয়া যাবে, আজকের সঙ্গে তুলনা করার জন্য। একই রকম সময় আর পরিস্থিতি রাখুন। বেশি পরীক্ষা করলেই নতুন সেন্সরের মাপ তৈরি হয় না, ভালো স্বাস্থ্যের নিশ্চয়তাও নেই।', numbers:'এবার আপনার মাপগুলি শুনুন।', summary:'আজ আপনার পরের পদক্ষেপ', share:'বন্ধুর সঙ্গে খেয়াল রাখুন', shareText:'বন্ধু বা সঙ্গীকে তার নিজের ব্যক্তিগত পরীক্ষায় আমন্ত্রণ জানান। নিয়মিত খেয়াল রাখার তুলনা করুন, কার শরীর ভালো তার নয়। শেয়ার করা আপনার ইচ্ছা।', noScore:'এই মাপ থেকে পুরো স্বাস্থ্যের নির্ভরযোগ্য স্কোর পাওয়া যায় না।' }
};
export const metricCopy = {
 height: [['Height','लंबाई','উচ্চতা'],['How tall you are.','आपकी लंबाई कितनी है।','আপনি কতটা লম্বা।'],'cm'],
 weight: [['Weight','वजन','ওজন'],['Your measured body weight.','आज मशीन पर आपका वजन।','আজ যন্ত্রে আপনার ওজন।'],'kg'],
 systolic: [['Systolic pressure','बीपी ऊपर वाला','বিপি উপরের মাপ'],['Pressure when your heart pumps.','दिल जब खून भेजता है, तब का दबाव।','হার্ট যখন রক্ত পাঠায়, তখনকার চাপ।'],'mmHg'],
 diastolic: [['Diastolic pressure','बीपी नीचे वाला','বিপি নিচের মাপ'],['Pressure between heartbeats.','दो धड़कनों के बीच का दबाव।','দুটি হার্টবিটের মাঝের চাপ।'],'mmHg'],
 bpm: [['Pulse','धड़कन','পালস'],['Heartbeats in one minute.','एक मिनट में दिल कितनी बार धड़का।','এক মিনিটে হার্ট কতবার চলেছে।'],'bpm'],
 oxygen: [['Oxygen','ऑक्सीजन','অক্সিজেন'],['Estimated oxygen in your blood. Movement and cold fingers affect the reading.','खून में ऑक्सीजन का अंदाजा। हिलने या उँगली ठंडी होने से रीडिंग बदल सकती है।','রক্তে অক্সিজেনের আন্দাজ। নড়লে বা আঙুল ঠান্ডা হলে রিডিং বদলাতে পারে।'],'%'],
 temperature: [['Temperature','शरीर की गर्मी','শরীরের তাপমাত্রা'],['Body temperature at the sensor site.','जहाँ सेंसर लगा था, वहाँ शरीर कितना गर्म था।','যেখানে সেন্সর ছিল, সেখানকার শরীরের তাপমাত্রা।'],'°F'],
 bmi: [['Body mass index','बीएमआई','বিএমআই'],['Weight relative to height. It does not directly measure body fat.','लंबाई के हिसाब से वजन। यह सीधे फैट नहीं मापता।','উচ্চতার তুলনায় ওজন। সরাসরি ফ্যাট মাপে না।'],'kg/m²'],
 bsa: [['Body surface area','शरीर का सतही क्षेत्र','শরীরের বাইরের ক্ষেত্রফল'],['Skin surface area calculated from height and weight.','लंबाई और वजन से शरीर की बाहरी सतह का हिसाब।','উচ্চতা আর ওজন থেকে বাইরের ক্ষেত্রফলের হিসাব।'],'m²'],
 restingEnergy: [['Resting energy','आराम में लगने वाली एनर्जी','বিশ্রামের এনার্জি'],['Estimated energy used at rest, not your daily food target.','आराम में लगने वाली एनर्जी का अंदाजा। पूरे दिन के खाने का टारगेट नहीं।','বিশ্রামের এনার্জির আন্দাজ। সারাদিনের খাবারের টার্গেট নয়।'],'kcal/day'],
 bodyFat: [['Body fat estimate','शरीर के फैट का अनुमान','শরীরের ফ্যাটের অনুমান'],['A formula estimate, not a body-fat sensor result.','फॉर्मूले से फैट का अंदाजा। फैट सेंसर की रीडिंग नहीं।','ফর্মুলা দিয়ে ফ্যাটের আন্দাজ। ফ্যাট সেন্সরের রিডিং নয়।'],'%'],
 fatMass: [['Fat mass estimate','फैट का वजन','ফ্যাটের ওজন'],['Estimated weight of body fat.','शरीर के फैट का अनुमानित वजन।','শরীরের ফ্যাটের আনুমানিক ওজন।'],'kg'],
 fatFreeMass: [['Fat-free mass estimate','फैट के अलावा वजन','ফ্যাট ছাড়া ওজন'],['Includes water, organs and bone. Not muscle alone.','पानी, अंग और हड्डियाँ भी इसमें हैं। सिर्फ मसल नहीं।','জল, অঙ্গ আর হাড়ও আছে। শুধু মাসল নয়।'],'kg'],
 ffmi: [['Fat-free mass index','बिना फैट वजन का इंडेक्स','ফ্যাট ছাড়া ওজনের ইনডেক্স'],['Estimated fat-free weight relative to height.','लंबाई के हिसाब से बिना फैट वाले वजन का अनुमान।','উচ্চতার তুলনায় ফ্যাট ছাড়া ওজনের অনুমান।'],'kg/m²'],
 bodyWaterLitres: [['Body water estimate','शरीर में पानी का अनुमान','শরীরের জলের অনুমান'],['Estimated water in the body. Cannot diagnose dehydration.','शरीर में पानी का अंदाजा। इससे पानी की कमी पक्के तौर पर नहीं पता चलती।','শরীরের জলের আন্দাজ। জল কমে গেছে কি না নিশ্চিত বলা যায় না।'],'L'],
 bodyWater: [['Body water share','वजन में पानी का हिस्सा','ওজনের মধ্যে জলের অংশ'],['Estimated water share, not a drinking target.','वजन में पानी का हिस्सा। पीने के पानी का टारगेट नहीं।','ওজনের মধ্যে জলের অংশ। জল খাওয়ার টার্গেট নয়।'],'%'],
};
export const languageIndex = lang => ({en:0,hi:1,bn:2}[lang] ?? 0);
