// Generic language building blocks. Patient values never appear in recordings.
export const personalizedReportCopy = {
 en: {
  pages: ['Let’s look at your body overview and today’s estimate.', 'Now let’s go through your actual readings and what they mean.', 'This page shows how your own readings have changed over your visits.', 'Here we compare today with your most recent matching scan, one measurement at a time.', 'Let’s put your results together and decide what deserves attention today.'],
  score: 'Your estimated health score on this screen is', scoreEnd: 'out of one hundred. This is a calculated screening summary, not a diagnosis. A high score does not cancel out an abnormal reading.',
  today: 'Your reading today is', previous: 'The earlier reading was', higher: 'The reading is higher by', lower: 'The reading is lower by', same: 'The recorded value is unchanged.', noEarlier: 'There is no earlier matching reading to compare yet.',
  noAssessment: 'There is not enough measured information here to say your results are reassuring. Missing readings need to be checked; they do not mean zero or normal.',
  noFlags: 'The readings with applicable adult reference ranges are within those ranges today. This is reassuring for those readings, but it does not rule out illness.',
  bp: 'For this blood pressure reading, sit quietly for five minutes, with your back supported, feet on the floor and arm supported at heart level. Repeat correctly and discuss a persistently unusual result with a clinician. Do not change your medicines yourself.',
  oxygen: 'For this oxygen reading, keep a warm finger still and check that the sensor fits properly. If it stays unusual, ask a clinician. Feeling breathless needs help even when the number looks normal.',
  pulse: 'For this pulse reading, rest quietly and check again. Activity and stress can change the number. If it stays unusual, or you feel unwell, ask a clinician.',
  temperature: 'Check this temperature again using the device instructions. The measurement site affects the reading. Ask a clinician if it remains unusual or you feel unwell.',
  bmiLow: 'Your BMI is below the adult reference range. It is a weight-to-height calculation, not a diagnosis. Discuss your eating pattern and any unintended weight loss with a clinician or dietitian; avoid trying a quick weight-change plan.',
  bmiHigh: 'Your BMI is above the adult reference range. It does not tell us how much muscle you have. A clinician or dietitian can help plan suitable meals and activity for you. Avoid crash diets.',
  estimates: 'These body fat and water values are estimates from your recorded details, not direct sensor measurements. They cannot tell us whether you are dehydrated or give you a food or water target.',
  next: 'Next time, these same measurements can be compared with today. Use similar timing and conditions. More records help show repeated changes; they do not automatically mean better health.',
 },
 hi: {
  pages: ['चलिए, पहले आपके शरीर की जानकारी और आज का अनुमान देखते हैं।', 'अब आपकी असली रीडिंग और उनका मतलब एक-एक करके समझते हैं।', 'इस पेज पर आपकी पिछली जाँचों से आज तक के बदलाव दिखते हैं।', 'यहाँ आज की रीडिंग को आपकी पिछली उपलब्ध रीडिंग से एक-एक करके मिलाते हैं।', 'अब आपकी रिपोर्ट को साथ में समझते हैं कि आज किस बात पर ध्यान देना है।'],
  score: 'इस स्क्रीन पर आपकी सेहत का अनुमानित स्कोर है', scoreEnd: 'सौ में से। यह हिसाब से बना स्कोर है, बीमारी की जाँच का फैसला नहीं। अच्छा स्कोर होने पर भी कोई गलत रीडिंग नजरअंदाज नहीं करनी है।',
  today: 'आज आपकी रीडिंग है', previous: 'पिछली रीडिंग थी', higher: 'रीडिंग इतनी बढ़ी है', lower: 'रीडिंग इतनी कम हुई है', same: 'दर्ज रीडिंग में बदलाव नहीं है।', noEarlier: 'इस माप की पिछली रीडिंग अभी नहीं है, इसलिए तुलना नहीं कर सकते।',
  noAssessment: 'अभी इतने असली माप नहीं मिले कि सब ठीक है कह सकें। जो रीडिंग नहीं मिली, उसे जाँचना होगा। खाली जगह का मतलब शून्य या सब ठीक नहीं है।',
  noFlags: 'जिन रीडिंग पर बड़ों की सामान्य रेंज लागू होती है, वे आज उस रेंज में हैं। उन मापों के लिए यह अच्छी बात है, लेकिन इससे हर बीमारी खारिज नहीं होती।',
  bp: 'इस बीपी के लिए पाँच मिनट आराम से बैठें। पीठ को सहारा दें, पैर जमीन पर रखें और हाथ दिल की ऊँचाई पर टिकाएँ। सही तरीके से फिर मापें। रीडिंग बार-बार अलग रहे तो डॉक्टर से बात करें। अपनी दवा खुद से न बदलें।',
  oxygen: 'ऑक्सीजन के लिए उँगली गर्म और स्थिर रखें, सेंसर सही लगा हो। रीडिंग अलग बनी रहे तो डॉक्टर से बात करें। साँस लेने में दिक्कत हो तो नंबर ठीक दिखने पर भी मदद लें।',
  pulse: 'धड़कन के लिए थोड़ा आराम करके फिर जाँचें। चलने-फिरने या टेंशन से नंबर बदल सकता है। रीडिंग अलग बनी रहे या तबीयत खराब हो तो डॉक्टर से बात करें।',
  temperature: 'डिवाइस के निर्देश के हिसाब से शरीर की गर्मी फिर जाँचें। सेंसर कहाँ लगाया है, उससे रीडिंग बदल सकती है। रीडिंग अलग बनी रहे या तबीयत खराब हो तो डॉक्टर से बात करें।',
  bmiLow: 'आपका बीएमआई बड़ों की सामान्य रेंज से कम है। यह लंबाई के हिसाब से वजन का हिसाब है, बीमारी का फैसला नहीं। खाने की आदतों और बिना कोशिश वजन घटने पर डॉक्टर या डाइटीशियन से बात करें। जल्दी वजन बदलने वाली योजना न अपनाएँ।',
  bmiHigh: 'आपका बीएमआई बड़ों की सामान्य रेंज से ऊपर है। इससे मसल की मात्रा नहीं पता चलती। डॉक्टर या डाइटीशियन आपके लिए सही खाना और एक्टिविटी तय करने में मदद कर सकते हैं। क्रैश डाइट न करें।',
  estimates: 'फैट और पानी की ये रीडिंग आपके दर्ज विवरण से निकले अनुमान हैं, सेंसर ने सीधे नहीं मापा। इनसे पानी की कमी या कितना खाना और पानी लेना है, यह तय नहीं होता।',
  next: 'अगली बार यही माप आज से मिलाकर देख सकते हैं। करीब वही समय और हालात रखें। ज्यादा रिकॉर्ड से बार-बार होने वाला बदलाव समझ आता है, अपने आप अच्छी सेहत का मतलब नहीं होता।',
 },
 bn: {
  pages: ['চলুন, আগে আপনার শরীরের তথ্য আর আজকের অনুমান দেখি।', 'এবার আপনার আসল রিডিং আর তার মানে এক-এক করে বুঝি।', 'এই পাতায় আপনার আগের পরীক্ষা থেকে আজ পর্যন্ত বদল দেখা যাচ্ছে।', 'এখানে আজকের রিডিং আপনার আগের পাওয়া রিডিংয়ের সঙ্গে এক-এক করে মেলাব।', 'এবার আপনার রিপোর্ট মিলিয়ে বুঝি, আজ কোন বিষয়ে খেয়াল রাখা দরকার।'],
  score: 'এই স্ক্রিনে আপনার স্বাস্থ্যের আনুমানিক স্কোর হল', scoreEnd: 'একশোর মধ্যে। এটি হিসাব করা স্কোর, রোগ নির্ণয় নয়। স্কোর ভালো হলেও অস্বাভাবিক রিডিং উপেক্ষা করবেন না।',
  today: 'আজ আপনার রিডিং হল', previous: 'আগের রিডিং ছিল', higher: 'রিডিং এতটা বেড়েছে', lower: 'রিডিং এতটা কমেছে', same: 'নথিভুক্ত রিডিং একই আছে।', noEarlier: 'এই মাপের আগের রিডিং নেই, তাই এখনও তুলনা করা যাচ্ছে না।',
  noAssessment: 'সব ঠিক আছে বলার মতো যথেষ্ট আসল মাপ পাওয়া যায়নি। যে রিডিং নেই তা মাপতে হবে। ফাঁকা মানে শূন্য বা স্বাভাবিক নয়।',
  noFlags: 'যে রিডিংগুলিতে বড়দের সাধারণ সীমা প্রযোজ্য, সেগুলি আজ সেই সীমায় আছে। ওই মাপগুলির জন্য এটি ভালো খবর, তবে এতে সব অসুখ নেই বলা যায় না।',
  bp: 'এই বিপির জন্য পাঁচ মিনিট শান্ত হয়ে বসুন। পিঠে ভর দিন, পা মেঝেতে রাখুন, হাত হার্টের উচ্চতায় ঠেকিয়ে রাখুন। ঠিকভাবে আবার মাপুন। রিডিং বারবার আলাদা থাকলে ডাক্তারের সঙ্গে কথা বলুন। নিজে থেকে ওষুধ বদলাবেন না।',
  oxygen: 'অক্সিজেন মাপার সময় আঙুল গরম আর স্থির রাখুন, সেন্সর ঠিকমতো লাগান। রিডিং অস্বাভাবিক থাকলে ডাক্তারকে জানান। শ্বাস নিতে কষ্ট হলে নম্বর স্বাভাবিক দেখালেও সাহায্য নিন।',
  pulse: 'পালসের জন্য একটু বিশ্রাম নিয়ে আবার মাপুন। হাঁটাচলা বা টেনশনে নম্বর বদলাতে পারে। রিডিং অস্বাভাবিক থাকলে বা শরীর খারাপ লাগলে ডাক্তারের সঙ্গে কথা বলুন।',
  temperature: 'যন্ত্রের নির্দেশ মেনে তাপমাত্রা আবার মাপুন। কোথায় মাপছেন তার ওপর রিডিং বদলাতে পারে। অস্বাভাবিক থাকলে বা শরীর খারাপ লাগলে ডাক্তারকে জানান।',
  bmiLow: 'আপনার বিএমআই বড়দের সাধারণ সীমার নিচে। এটি উচ্চতার তুলনায় ওজনের হিসাব, রোগ নির্ণয় নয়। খাবারের অভ্যাস বা চেষ্টা ছাড়াই ওজন কমলে ডাক্তার বা ডায়েটিশিয়ানের সঙ্গে কথা বলুন। তাড়াতাড়ি ওজন বদলানোর পরিকল্পনা এড়িয়ে চলুন।',
  bmiHigh: 'আপনার বিএমআই বড়দের সাধারণ সীমার ওপরে। এতে মাসলের পরিমাণ বোঝা যায় না। ডাক্তার বা ডায়েটিশিয়ান আপনার উপযুক্ত খাবার আর চলাফেরার পরিকল্পনায় সাহায্য করতে পারেন। ক্র্যাশ ডায়েট করবেন না।',
  estimates: 'ফ্যাট আর জলের এই মান আপনার নথিভুক্ত তথ্য থেকে করা অনুমান, সেন্সরে সরাসরি মাপা নয়। এতে জল কমে গেছে কি না, বা কতটা খাবার আর জল দরকার, তা ঠিক করা যায় না।',
  next: 'পরের বার একই মাপ আজকের সঙ্গে মেলাতে পারবেন। একই রকম সময় আর পরিস্থিতি রাখুন। বেশি রেকর্ডে বারবার হওয়া বদল বোঝা যায়, নিজে থেকেই ভালো স্বাস্থ্য বোঝায় না।',
 }
};
